[package]
name = "tokio_ex"
version = "0.1.0"
authors = ["Vladimir Beliaev <vladbel@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.25"
tokio = "0.1.18"
tokio-core = "0.1.17"